# Use an official lightweight Node.js image.
FROM node:22-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install the production dependencies only
RUN npm install --only=production

# Keep the container running
CMD ["sh"]
